package com.gitrose.mobile.constant;

import android.graphics.Bitmap.Config;
import android.graphics.PointF;
import android.os.Environment;
import com.nostra13.universalimageloader.core.DisplayImageOptions;
import com.nostra13.universalimageloader.core.DisplayImageOptions.Builder;
import com.nostra13.universalimageloader.core.assist.ImageScaleType;
import com.gitrose.mobile.R;
import com.gitrose.mobile.ChoiseHiddenModeActivity;
import com.gitrose.mobile.application.MyApplication;
import com.gitrose.mobile.http.ConstantURL;

public class Constant {
    public static final String ACTION_READ_APPLY = "com.gitrose.mobile.action.sync.friends.apply.read";
    public static final String ACTION_SHARE_TO_SOCIAL = "com.gitrose.mobile.action.share.to.social";
    public static final String ACTION_SYNC_SELF_ALL = "com.gitrose.mobile.action.sync.all";
    public static final String ACTION_SYNC_SELF_FRIENDS = "com.gitrose.mobile.action.sync.friends";
    public static final String ACTION_SYNC_SELF_INFO = "com.gitrose.mobile.action.sync.info";
    public static final String ACTION_SYNC_SELF_TOPIC = "com.gitrose.mobile.action.sync.topic";
    public static final String ACTION_SYNC_UI = "com.gitrose.mobile.action.sync.ui";
    public static final String ADD_FAV_TOPIC_ACTION = "com.gitrose.mobile.add_fav_topic_action";
    public static final String APP_CACHE_DIR_NAME = "tutu";
    public static final String APP_CACHE_DIR_NAME2 = "Tutu";
    public static DisplayImageOptions AVATAR_OPTIONS = null;
    public static final String AVATAR_TIME_PERFERENCE = "avatarTime";
    public static final String AV_ACCOUNTTYPE = "759";
    public static final int AV_APPID = 1400001474;
    public static DisplayImageOptions BIG_PICTURE_OPTIONS = null;
    public static final String BLOCK_PRIVATE_ACTION = "com.gitrose.mobile.block_private_action";
    public static final String BLOCK_TOPIC_ACTION = "com.gitrose.mobile.block_topic_action";
    public static final String BUGLY_APP_KEY = "900006213";
    public static final String CHANNEL_ALIPAY = "alipay";
    public static final String CHANNEL_WECHAT = "wx";
    public static final int COMMENT_KUANG_HEIGHT = 28;
    public static final int COMMENT_KUANG_WIDTH = 10;
    public static final Integer CURRENT_0;
    public static final Integer CURRENT_1;
    public static final String DAREN_CLICK = "daren_click";
    public static final String DATABASE_NAME = "TUTU_db";
    public static final float DEFAULT_BACKOFF_MULT = 1.0f;
    public static final int DEFAULT_MAX_RETRIES = 2;
    public static final int DEFAULT_TIMEOUT_MS = 2500;
    public static final String DEL_FAV_TOPIC_ACTION = "com.gitrose.mobile.del_fav_topic_action";
    public static final String DEL_REPOST_TOPIC_ACTION = "com.gitrose.mobile.del_repost_topic_action";
    public static final String DEL_TOPIC_ACTION = "com.gitrose.mobile.del_topic_action";
    public static final int DEMO_ERROR_BASE = -99999999;
    public static final int DEMO_ERROR_NULL_POINTER = -99999998;
    public static String DOMAIN = null;
    public static final String FAV_THEME = "favlist";
    public static final int FEMALE = 2;
    public static final long FILE_SIZE = 4194304;
    public static final String FILE_START_NAME = "VMS_";
    public static final int FLV = 1;
    public static final String FOLLOW_TOPIC_ACTION = "com.gitrose.mobile.follow_topic_action";
    public static final String FOLLOW_USER_ACTION = "com.gitrose.mobile.follow_user_action";
    public static final String FROM_REPOST = "1";
    public static final String HEAD_BIG_SIZE = "/100";
    public static final String HEAD_MAX_SIZE = "/176";
    public static final String HEAD_SMALL_SIZE = "/80";
    public static final int HLS = 2;
    public static final String HUATI_GUANGCHANG = "http://www.gitrose.com/hd/hothuatih5.php";
    public static String IMAGE_DOWNLOAD_REFERER = null;
    public static final String IMAGE_EXTENSION = ".jpg";
    public static DisplayImageOptions INPUT_OPTIONS = null;
    public static final String IS_BIND_PHONE = "isbind_phone";
    public static final String IS_BIND_QQ = "isbind_qq";
    public static final String IS_BIND_WEIBO = "isbind_weibo";
    public static final int IS_BLOCK = 1;
    public static final Integer IS_DEL_0;
    public static final Integer IS_DEL_1;
    public static final String KEY_DELETE_FOLDER_FROM_SDCARD = "deleteFolderFromSDCard";
    public static final String KEY_HOME_GUIDE = "homeGuide";
    public static final String KEY_ISFIRST = "isFirst";
    public static DisplayImageOptions LEVEL_OPTIONS = null;
    public static final String LIVE_CUSTOM_TYPE_ANCHOR_BREAK = "anchor_break";
    public static final String LIVE_CUSTOM_TYPE_ENTERROOM = "enterroom";
    public static final String LIVE_CUSTOM_TYPE_EXITROOM = "exitroom";
    public static final String LIVE_CUSTOM_TYPE_FOLLOW = "follow";
    public static final String LIVE_CUSTOM_TYPE_LIKE = "like";
    public static final String LIVE_CUSTOM_TYPE_LIVE_BREAK = "live_break";
    public static final String LIVE_CUSTOM_TYPE_PRESENT = "present";
    public static final String LIVE_CUSTOM_TYPE_UNFOLLOW = "unfollow";
    public static DisplayImageOptions LIVE_PICTURE_OPTIONS = null;
    public static final String LOADING_PIC_URL = "loading_pic_url";
    public static final String LOCATION_STATUS = "locationStatus";
    public static final String LOGIN_TYPE = "logintype";
    public static final int MALE = 1;
    public static final String METADATA_REQUEST_BUNDLE_TAG = "requestMetaData";
    public static final String MODIFY_MARKNAME_ACTION = "com.gitrose.mobile.modify_markname_action";
    public static final int NET_3G = 0;
    public static final String NICK_NAME_PERFERENCE = "nickName";
    public static final int NO_NET = -1;
    public static final String PLAY_SOUND_PERFERENCE = "Tutu_preference";
    public static final String PREFENCES_NAME = "tutu";
    public static final String PUSH_HOME_FOLLOW_ACTION = "com.gitrose.mobile.push_home_follow_action";
    public static final String QQ_APP_ID = "1103429136";
    public static final String RC_TOLEN = "rctoken";
    public static final String RECEIVER_ACTION_SAVE_FRAME = "com.javacv.recorder.intent.action.SAVE_FRAME";
    public static final String RECEIVER_CATEGORY_SAVE_FRAME = "com.javacv.recorder";
    public static final String REDPACKAGRE_HOME_FOLLOW_ACTION = "com.gitrose.mobile.redpackage_home_follow_action";
    public static final String REFRESH_FOLLOW_TOPIC_ACTION = "com.gitrose.mobile.refresh_follow_topic_action";
    public static final String REFRESH_UNFOLLOW_TOPIC_ACTION = "com.gitrose.mobile.other_unfollow_topic_action";
    public static final Integer RELATION_0;
    public static final Integer RELATION_1;
    public static final Integer RELATION_2;
    public static final Integer RELATION_3;
    public static final Integer RELATION_4;
    public static final Integer RELATION_5;
    public static final Integer RELATION_6;
    public static final String REPOST_TOPIC_ACTION = "com.gitrose.mobile.repost_topic_action";
    public static final int RESOLUTION_HIGH = 1300;
    public static final int RESOLUTION_HIGH_VALUE = 2;
    public static final int RESOLUTION_LOW = 180;
    public static final int RESOLUTION_LOW_VALUE = 0;
    public static final int RESOLUTION_MEDIUM = 500;
    public static final int RESOLUTION_MEDIUM_VALUE = 1;
    public static final int RTMP = 5;
    public static final String SINA_APP_KEY = "367414361";
    public static final String SINA_REDIRECT_URL = "http://sns.whalecloud.com/sina2/callback";
    public static final String SINA_SCOPE = "email,direct_messages_read,direct_messages_write,friendships_groups_read,friendships_groups_write,statuses_to_me_read,follow_app_official_microblog,invitation_write";
    public static DisplayImageOptions SMALL_PICTURE_OPTIONS = null;
    public static DisplayImageOptions SMALL_PICTURE_OPTIONS_GRAY = null;
    public static DisplayImageOptions SMALL_PICTURE_OPTIONS_WHITE = null;
    public static final String SO_ENABLE = "so_enable";
    public static final String SO_FLAG = "so_flag";
    public static final String SP_LIVE_SIGN = "sp_live_sign";
    public static final String SYSTEM_UID = "1";
    public static final String TAG_SAVE_FRAME = "saveFrame";
    public static final String TOKEN = "tutu_token";
    public static String TWITTER_CALL_BACK = null;
    public static final String TWITTER_KEY = "Zu3QTDezU2kKnkZwB6F2bzoec";
    public static final String TWITTER_OAUTH = "oauth_verifier";
    public static final String TWITTER_SECRET = "B0XIEsRdUnDmLl0OGQTzPjYZ9EWEjB9yuRvM81e4Y8nhgEvMDA";
    public static final String UID = "tutu_uid";
    public static final String UNBLOCK_PRIVATE_ACTION = "com.gitrose.mobile.unblock_private_action";
    public static final String UNBLOCK_TOPIC_ACTION = "com.gitrose.mobile.unblock_topic_action";
    public static final String UNFOLLOW_TOPIC_ACTION = "com.gitrose.mobile.unfollow_topic_action";
    public static final String UNFOLLOW_USER_ACTION = "com.gitrose.mobile.unfollow_user_action";
    public static final String UNFROM_REPOST = "0";
    public static final int UN_BLOCK = 0;
    public static final String UPLOAD_TOPIC_ACTION = "com.gitrose.mobile.add_topic_action";
    public static final String UPLOAD_TOPIC_FINISH_ACTION = "com.gitrose.mobile.add_topic_finish_action";
    public static final String UPLOAD_WALL_PIC = "com.gitrose.mobile.upload_wall";
    public static final String VIDEO_CONTENT_URI = "content://media/external/video/media";
    public static final String VIDEO_EXTENSION = ".mp4";
    public static String VOICE_PATH = null;
    public static DisplayImageOptions WALL_PICTURE_OPTIONS = null;
    public static final int WIFI = 1;
    public static final String WORK_THEME = "publishlist";
    public static int XG_NOTIFY_ADD_FRIENDS_TYPE = 0;
    public static int XG_NOTIFY_COMMENT_AT_TYPE = 0;
    public static int XG_NOTIFY_COMMENT_TYPE = 0;
    public static int XG_NOTIFY_DEFAULT_TYPE = 0;
    public static int XG_NOTIFY_FOLLOW_ME = 0;
    public static int XG_NOTIFY_HOME_FOLLOW = 0;
    public static int XG_NOTIFY_LIKE_USER_TYPE = 0;
    public static int XG_NOTIFY_PRIVAT_CHAT_TYPE = 0;
    public static int XG_NOTIFY_PUBLISHLIVE = 0;
    public static int XG_NOTIFY_REPOST_TOPIC_TYPE = 0;
    public static int XG_NOTIFY_SYS_HUATI = 0;
    public static int XG_NOTIFY_SYS_NEAR = 0;
    public static int XG_NOTIFY_SYS_POI = 0;
    public static int XG_NOTIFY_SYS_TO_USER_HOME = 0;
    public static int XG_NOTIFY_TOPIC_AT_TYPE = 0;
    public static int XG_NOTIFY_ZAN_TYPE = 0;
    public static String XG_TYPE_ADD_FRIENDS = null;
    public static String XG_TYPE_BLOCK = null;
    public static String XG_TYPE_COMMENT = null;
    public static String XG_TYPE_COMMENT_AT = null;
    public static String XG_TYPE_FOLLOW_ME = null;
    public static String XG_TYPE_HOME_FOLLOW = null;
    public static String XG_TYPE_LIKE_COMMENT = null;
    public static String XG_TYPE_LIKE_USER = null;
    public static String XG_TYPE_PRIVAT_CHAT = null;
    public static String XG_TYPE_PUBLISHLIVE = null;
    public static String XG_TYPE_REPLAY_COMMENT = null;
    public static String XG_TYPE_REPOST_TOPIC = null;
    public static String XG_TYPE_SYS_HTTP = null;
    public static String XG_TYPE_SYS_HUATI = null;
    public static String XG_TYPE_SYS_NEAR = null;
    public static String XG_TYPE_SYS_POI = null;
    public static String XG_TYPE_SYS_TOPIC_DETAIL = null;
    public static String XG_TYPE_SYS_TO_USER_HOME = null;
    public static String XG_TYPE_TOPIC_AT = null;
    public static String XG_TYPE_UNBLOCK = null;
    public static String XG_TYPE_ZAN = null;
    public static final String ZAN_TOPIC_ACTION = "com.gitrose.mobile.zan_topic_action";
    public static final String accessKey = "UBD2COzG3TJy6qus";
    public static int animation_1 = 0;
    public static int animation_2 = 0;
    public static final int crop_pic_toast_id = 1;
    public static float mRotate = 0.0f;
    public static float mScale = 0.0f;
    public static PointF midF = null;
    public static int netWorkStatus = 0;
    public static final String picBucketName = "tutupic";
    public static final String screctKey = "kcQUIYjqhLR8VCdT1ejwLLQzyHH2VL";
    public static final String srcFileDir = "<your data directory>/";
    public static final String videoBucketName = "tutuvideo";

    static {
        DOMAIN = "www.gitrose.com";
        IMAGE_DOWNLOAD_REFERER = ConstantURL.DOMAIN_SHARE;
        TWITTER_CALL_BACK = "http//www.gitrose.com";
        XG_TYPE_ZAN = LIVE_CUSTOM_TYPE_LIKE;
        XG_TYPE_ADD_FRIENDS = ChoiseHiddenModeActivity.FRIEND_MODE;
        XG_TYPE_COMMENT = "comment";
        XG_TYPE_PRIVAT_CHAT = "message";
        XG_TYPE_LIKE_USER = "likeuser";
        XG_TYPE_LIKE_COMMENT = "likecomment";
        XG_TYPE_SYS_TOPIC_DETAIL = "systopicdetail";
        XG_TYPE_SYS_HTTP = "syshttp";
        XG_TYPE_BLOCK = "block";
        XG_TYPE_UNBLOCK = "unblock";
        XG_TYPE_TOPIC_AT = "topicatuser";
        XG_TYPE_COMMENT_AT = "commentatuser";
        XG_TYPE_REPOST_TOPIC = "reposttopic";
        XG_TYPE_FOLLOW_ME = LIVE_CUSTOM_TYPE_FOLLOW;
        XG_TYPE_REPLAY_COMMENT = "replycomment";
        XG_TYPE_HOME_FOLLOW = "showhomefollowlist";
        XG_TYPE_SYS_TO_USER_HOME = "sysuserhomepage";
        XG_TYPE_SYS_HUATI = "syshuati";
        XG_TYPE_SYS_POI = "syspoi";
        XG_TYPE_SYS_NEAR = "sysnear";
        XG_TYPE_PUBLISHLIVE = "publishlive";
        XG_NOTIFY_DEFAULT_TYPE = NO_NET;
        XG_NOTIFY_ZAN_TYPE = UN_BLOCK;
        XG_NOTIFY_COMMENT_TYPE = crop_pic_toast_id;
        XG_NOTIFY_ADD_FRIENDS_TYPE = RESOLUTION_HIGH_VALUE;
        XG_NOTIFY_PRIVAT_CHAT_TYPE = 3;
        XG_NOTIFY_LIKE_USER_TYPE = 4;
        XG_NOTIFY_TOPIC_AT_TYPE = RTMP;
        XG_NOTIFY_COMMENT_AT_TYPE = 6;
        XG_NOTIFY_REPOST_TOPIC_TYPE = 7;
        XG_NOTIFY_FOLLOW_ME = 8;
        XG_NOTIFY_SYS_TO_USER_HOME = 9;
        XG_NOTIFY_SYS_HUATI = COMMENT_KUANG_WIDTH;
        XG_NOTIFY_SYS_POI = 11;
        XG_NOTIFY_SYS_NEAR = 12;
        XG_NOTIFY_HOME_FOLLOW = 13;
        XG_NOTIFY_PUBLISHLIVE = 14;
        RELATION_0 = Integer.valueOf(UN_BLOCK);
        RELATION_1 = Integer.valueOf(crop_pic_toast_id);
        RELATION_2 = Integer.valueOf(RESOLUTION_HIGH_VALUE);
        RELATION_3 = Integer.valueOf(3);
        RELATION_4 = Integer.valueOf(4);
        RELATION_5 = Integer.valueOf(RTMP);
        RELATION_6 = Integer.valueOf(6);
        CURRENT_0 = Integer.valueOf(UN_BLOCK);
        CURRENT_1 = Integer.valueOf(crop_pic_toast_id);
        IS_DEL_0 = Integer.valueOf(UN_BLOCK);
        IS_DEL_1 = Integer.valueOf(crop_pic_toast_id);
        VOICE_PATH = Environment.getExternalStorageDirectory() + "/tutu/voice";
        LEVEL_OPTIONS = new Builder().showStubImage(R.drawable.userhonorlevel1).showImageForEmptyUri((int) R.drawable.userhonorlevel1).cacheOnDisk(true).cacheInMemory(MyApplication.getInstance().is_max_version).showImageOnFail((int) R.drawable.userhonorlevel1).build();
        AVATAR_OPTIONS = new Builder().showStubImage(R.drawable.default_avatar_bg).showImageForEmptyUri((int) R.drawable.default_avatar_bg).imageScaleType(ImageScaleType.IN_SAMPLE_POWER_OF_2).cacheOnDisk(true).cacheInMemory(MyApplication.getInstance().is_max_version).showImageOnFail((int) R.drawable.default_avatar_bg).build();
        BIG_PICTURE_OPTIONS = new Builder().showStubImage(R.drawable.img_logo_01).showImageForEmptyUri((int) R.drawable.img_logo_01).bitmapConfig(Config.RGB_565).cacheOnDisk(true).cacheInMemory(MyApplication.getInstance().is_max_version).showImageOnFail((int) R.drawable.img_logo_01).build();
        LIVE_PICTURE_OPTIONS = new Builder().showStubImage(R.drawable.home_live_bg).showImageForEmptyUri((int) R.drawable.home_live_bg).bitmapConfig(Config.RGB_565).cacheOnDisk(true).cacheInMemory(MyApplication.getInstance().is_max_version).showImageOnFail((int) R.drawable.home_live_bg).build();
        WALL_PICTURE_OPTIONS = new Builder().showStubImage(R.drawable.personal_wall_bg).showImageForEmptyUri((int) R.drawable.personal_wall_bg).cacheOnDisk(true).cacheInMemory(MyApplication.getInstance().is_max_version).showImageOnFail((int) R.drawable.personal_wall_bg).build();
        SMALL_PICTURE_OPTIONS = new Builder().showStubImage(R.drawable.default_pic_bg_small).showImageForEmptyUri((int) R.drawable.default_pic_bg_small).showImageOnFail((int) R.drawable.default_pic_bg_small).cacheInMemory(MyApplication.getInstance().is_max_version).cacheOnDisk(true).imageScaleType(ImageScaleType.IN_SAMPLE_POWER_OF_2).build();
        SMALL_PICTURE_OPTIONS_WHITE = new Builder().showStubImage(R.drawable.default_pic_bg_small_white).showImageForEmptyUri((int) R.drawable.default_pic_bg_small_white).showImageOnFail((int) R.drawable.default_pic_bg_small_white).cacheInMemory(MyApplication.getInstance().is_max_version).cacheOnDisk(true).imageScaleType(ImageScaleType.IN_SAMPLE_POWER_OF_2).build();
        SMALL_PICTURE_OPTIONS_GRAY = new Builder().showStubImage(R.color.home_bg).showImageForEmptyUri((int) R.color.home_bg).showImageOnFail((int) R.color.home_bg).cacheInMemory(MyApplication.getInstance().is_max_version).cacheOnDisk(true).imageScaleType(ImageScaleType.IN_SAMPLE_POWER_OF_2).build();
        animation_1 = R.anim.main_translatex100to0;
        animation_2 = R.anim.main_translatex0tof100;
        netWorkStatus = UN_BLOCK;
        mScale = DEFAULT_BACKOFF_MULT;
        mRotate = 0.0f;
        INPUT_OPTIONS = new Builder().showStubImage(R.drawable.comment_input_01).showImageForEmptyUri((int) R.drawable.comment_input_01).cacheOnDisk(true).cacheInMemory(MyApplication.getInstance().is_max_version).showImageOnFail((int) R.drawable.comment_input_01).build();
    }
}
